version: '3.9'
services:
  go_auth_app:
    container_name: go_auth_app
    build: .
    ports:
      - "8600:8080"
    volumes:
      - .:/usr/src/app
    depends_on: 
      - auth_pgsql_db
  auth_pgsql_db:
    container_name: auth_pgsql_db
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=jwt_auth_db
    ports: 
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment: 
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
        - "5480:80"
      depends_on: 
        - auth_pgsql_db
volumes:
  postgres_data: